# Path: src/robot/robotic_arm_v3_config/config/moveit_controllers.yaml

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - robotic_arm_controller
    - hand_controller

  # The Main Arm Controller
  robotic_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4

  # The Gripper Controller
  hand_controller:
    type: GripperCommand
    action_ns: gripper_cmd
    default: true
    joints:
      - end_effector_joint