cmake_minimum_required(VERSION 3.16)
project(mujoco_sim_plugins)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(pluginlib REQUIRED)
find_package(std_msgs REQUIRED)
find_package(mujoco_ros2_control_plugins REQUIRED)

find_package(mujoco_vendor QUIET)
if(mujoco_vendor_FOUND)
  set(MUJOCO_LIB mujoco::mujoco)
  set(MUJOCO_INCLUDE_DIR ${mujoco_vendor_INCLUDE_DIRS})
else()
  message(FATAL_ERROR "mujoco_vendor not found!")
endif()

add_library(mujoco_sim_plugins SHARED
  src/reset_plugin.cpp
)
target_include_directories(mujoco_sim_plugins PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
  $<INSTALL_INTERFACE:include>
)
target_include_directories(mujoco_sim_plugins SYSTEM PUBLIC
  $<BUILD_INTERFACE:${MUJOCO_INCLUDE_DIR}>
)
target_link_libraries(mujoco_sim_plugins PUBLIC
  ${MUJOCO_LIB}
  rclcpp::rclcpp
  pluginlib::pluginlib
  ${std_msgs_TARGETS}
  ${mujoco_ros2_control_plugins_TARGETS}
)

install(TARGETS mujoco_sim_plugins
  LIBRARY DESTINATION lib
  ARCHIVE DESTINATION lib
  RUNTIME DESTINATION bin
)

install(DIRECTORY include/
  DESTINATION include
)

pluginlib_export_plugin_description_file(mujoco_ros2_control_plugins mujoco_sim_plugins.xml)

ament_export_include_directories(include)
ament_export_dependencies(mujoco_vendor rclcpp pluginlib std_msgs mujoco_ros2_control_plugins)

ament_package()
