# Default initial positions for robotic_arm_model_v3's ros2_control fake system

initial_positions:
  end_effector_bottom_joint: 0
  end_effector_joint: 0
  end_effector_top_joint: 0
  joint_1: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0