<package format="3">
  <name>moveit_controls</name>
  <version>0.0.0</version>
  <description>Python MoveIt control nodes</description>

  <maintainer email="andre@example.com">andre</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>moveit_ros_planning_interface</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
